package org.example.database

import java.sql.Connection

fun createTables(connection: Connection) {
    connection.createStatement().use { statement ->
        statement.executeUpdate(
            """
            CREATE TABLE IF NOT EXISTS nodes (
                id VARCHAR(50) PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                node_type VARCHAR(50) NOT NULL
            )
            """.trimIndent()
        )

        statement.executeUpdate(
            """
            CREATE TABLE IF NOT EXISTS links (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_node_id VARCHAR(50) NOT NULL,
                target_node_id VARCHAR(50) NOT NULL,

                CONSTRAINT fk_links_source_node
                    FOREIGN KEY (source_node_id)
                    REFERENCES nodes(id),

                CONSTRAINT fk_links_target_node
                    FOREIGN KEY (target_node_id)
                    REFERENCES nodes(id)
            )
            """.trimIndent()
        )

        statement.executeUpdate(
            """
            CREATE TABLE IF NOT EXISTS events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                node_id VARCHAR(50) NOT NULL,
                target_node_id VARCHAR(50),
                event_type VARCHAR(50) NOT NULL,
                event_time TIMESTAMP NOT NULL,

                CONSTRAINT fk_events_node
                    FOREIGN KEY (node_id)
                    REFERENCES nodes(id),

                CONSTRAINT fk_events_target_node
                    FOREIGN KEY (target_node_id)
                    REFERENCES nodes(id)
            )
            """.trimIndent()
        )
    }
}